name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload via FTP
      uses: sebastianpopp/ftp-deploy-action@v1.1.0
      with:
        server: ftpupload.net
        username: if0_38083790
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        remote-dir: /htdocs
