name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # 监听主分支提交事件

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install lftp
      run: sudo apt-get install -y lftp

    - name: Deploy to InfinityFree
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -c "
        open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
        mirror --reverse --delete --verbose ./ ./;
        bye
        "
