    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.5.0
      with:
        server: ftp://your-ftp-server.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # 本地上传的文件夹
