name: FTP Deploy

on:
  push:
    branches:
      - main  # 在 main 分支推送时触发工作流

jobs:
  deploy:
    runs-on: self-hosted  # 或 ubuntu-latest，取决于是否使用 GitHub Runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # 拉取仓库代码

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.5.0  # 使用 FTP Deploy Action
        with:
          server: ${{ secrets.FTP_SERVER }}  # 从 Secrets 加载 FTP 信息
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # 要上传的本地目录
          server-dir: /htdocs/  # InfinityFree 的目标目录
