- name: Deploy to FTP server
  uses: SamKirkland/FTP-Deploy-Action@4.3.0
  with:
    server: ftpupload.net
    username: ${{ secrets.USERNAME }}
    password: ${{ secrets.PASSWORD }}
    local-dir: ./html
    server-dir: /htdocs
