- name: Upload via FTP
  uses: SamKirkland/FTP-Deploy-Action@4.3.2
  with:
    server: "ftpupload.net"
    username: ${{ secrets.FTP_USERNAME }}  # Secrets 引用
    password: ${{ secrets.FTP_PASSWORD }}
    local-dir: "./"  # 本地需要上传的文件夹
    server-dir: "/htdocs/"  # FTP 的目标目录
